//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HumanRMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class attendance
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public attendance()
        {
            this.emp_leaves = new HashSet<emp_leaves>();
            this.holidays = new HashSet<holiday>();
        }
    
        public int att_id { get; set; }
        public System.DateTime att_date { get; set; }
        public System.TimeSpan att_clock_in { get; set; }
        public System.TimeSpan att_clock_out { get; set; }
        public Nullable<int> att_fk_emp_id { get; set; }
        public string att_work { get; set; }
    
        public virtual employee_info employee_info { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<emp_leaves> emp_leaves { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<holiday> holidays { get; set; }
    }
}
