//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HumanRMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class emp_leaves
    {
        public int leave_id { get; set; }
        public int leave_yearly { get; set; }
        public int deducated_leave { get; set; }
        public int remaining_leave { get; set; }
        public Nullable<int> leave_fk_emp_id { get; set; }
        public Nullable<int> leave_fk_att_id { get; set; }
    
        public virtual attendance attendance { get; set; }
        public virtual employee_info employee_info { get; set; }
    }
}
