//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HumanRMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee_info
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public employee_info()
        {
            this.attendances = new HashSet<attendance>();
            this.emp_leaves = new HashSet<emp_leaves>();
            this.holidays = new HashSet<holiday>();
        }
    
        public int emp_id { get; set; }
        public string emp_fname { get; set; }
        public string emp_lname { get; set; }
        public string emp_cnic { get; set; }
        public string emp_gender { get; set; }
        public string emp_email { get; set; }
        public string emp_mobile { get; set; }
        public Nullable<int> emp_salary { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<attendance> attendances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<emp_leaves> emp_leaves { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<holiday> holidays { get; set; }
    }
}
