//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HumanRMS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HRMSEntities : DbContext
    {
        public HRMSEntities()
            : base("name=HRMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin_log> admin_log { get; set; }
        public virtual DbSet<attendance> attendances { get; set; }
        public virtual DbSet<emp_leaves> emp_leaves { get; set; }
        public virtual DbSet<employee_info> employee_info { get; set; }
        public virtual DbSet<holiday> holidays { get; set; }
        public virtual DbSet<hrdepartment> hrdepartments { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<notice_info> notice_info { get; set; }
    }
}
