//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HumanRMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class notice_info
    {
        public int notice_id { get; set; }
        public string notice_subject { get; set; }
        public System.DateTime notice_date { get; set; }
        public System.TimeSpan notice_time { get; set; }
        public string notice_dis { get; set; }
    }
}
